// TRANSLATION *************************************************************************************
// *************************************************************************************************

const displayGameTitle = 'PRAEDIUM';
let displayGameEdition = '';

const currencySymbol = '<s>𝐼</s>';

let displayIUnderstand = '';
let displayOK = '';
let displayOptions = '';
let displayMusic = '';
let displaySounds = '';
let displayAnimations = '';
let displayInStock = '';
let displayStaff = '';
let displayFieldhands = '';
let displayHireHand = '';
let displayCrop = '';
let displayAcresFarmed = '';
let displayHarvested = '';
let displayHarvest = '';
let displaySpent = '';
let displayStarving = '';
let displayStarvingHorse = '';
let displayRatPlague = '';
let displayCentury = '';
let displayDecade = '';
let displayYear = '';
let displaySemester = '';
let displaySeason = '';
let displayMonth = '';
let displayFortnight = '';
let displayWeek = '';
let displayDay = '';
let displayLabelAvailable = '';
let displayWheat = '';
let displayBarley = '';
let displayOlive = '';
let displayDate = '';
let displayFig = '';
let displayPomegranate = '';
let displayGrape = '';
let displayLogs = '';
let displayBoards = '';
let displayLumberjacks = '';
let displaySawyers = '';
let displayStone = '';
let displayOre = '';
let displayCopper = '';
let displayVignerons = '';
let displayArborists = '';
let displayHorticulturalists = '';
let displayMasons = '';
let displayMiners = '';
let displayCindermen = '';
let displayMetallurgists = '';
let displayGood = '';
let displayScoreProduced = '';
let displayScoreSpent = '';
let displayHomersProduced = '';
let displayHomersSpent = '';

let displayLabelBuyLand0 = '';
let displayLabelBuyLand1 = '';
let displayLabelBuyLand2 = '';
let displayHireAccountant = '';
let displayLabelBuyLand3 = '';
let displayLabelBuyLand4 = '';
let displayLabelBuyLand5 = '';
let displayLabelBuyLand6 = '';
let displayLabelBuyLand7 = '';
let displayLabelBuyLand8 = '';
let displayLabelBuyLand9 = '';
let displayLabelBuyLand10 = '';
let displayLabelForest = '';
let displayLabelLogCamp = '';
let displayLabelSawmill = '';
let displayLabelBuyLand11 = '';
let displayLabelBuyLand12 = '';
let displayLabelBuyLand13 = '';
let displayLabelQuarry = '';
let displayLabelBuyLand14 = '';
let displayLabelBuyLand15 = '';
let displayLabelBuyLand16 = '';
let displayLabelBuyLand17 = '';

let displayLabelRentWarehouse0 = '';
let displayLabelRentWarehouse1 = '';
let displayLabelRentWarehouse2 = '';

let displayLabelWasteTime = '';
let displayLabelResidence00 = '';
let displayLabelResidence01 = '';
let displayLabelResidence02 = '';
let displayLabelResidence03 = '';
let displayLabelResidence04 = '';
let displayLabelResidence05 = '';
let displayLabelResidence06 = '';
let displayLabelResidence07 = '';
let displayLabelResidence08 = '';
let displayLabelResidence09 = '';
let displayLabelResidence10 = '';
let displayLabelResidence11 = '';
let displayLabelResidence12 = '';
let displayLabelResidence13 = '';

let displayLabelFound = '';
let displayLabelBuild0 = '';
let displayLabelBuild1 = '';
let displayLabelBuild2 = '';
let displayLabelBuild3 = '';
let displayLabelMineScout = '';
let displayLabelMineDig = '';
let displayLabelFoundry = '';
let displayLabelBuild4 = '';
let displayLabelBuild5 = '';
let displayLabelBuild6 = '';
let displayLabelBuild7 = '';
let displayLabelBuild8 = '';
let displayLabelBuild9 = '';
let displayLabelBuild10 = '';
let displayLabelBuild11 = '';
let displayLabelBuild12 = '';
let displayLabelBuild13 = '';
let displayLabelBuild14 = '';
let displayLabelBuild15 = '';
let displayLabelBuild16 = '';
let displayLabelBuild17 = '';

let displayStoryFarm0 = '';
let displayStoryFarmMildew = '';
let displayStoryFarm1 = '';
let displayStoryFarm2 = '';
let displayStoryAccountant = '';
let displayStoryFarm3 = '';
let displayStoryFarm4 = '';
let displayStoryFarm5 = '';
let displayStoryFarm6 = '';
let displayStoryFarm7 = '';
let displayStoryFarm8 = '';
let displayStoryFarm9 = '';
let displayStoryFarm10 = '';
let displayStoryForest = '';
let displayStoryLoggingCamp = '';
let displayStorySawmill = '';
let displayStoryFarm11 = '';
let displayStoryFarm12 = '';
let displayStoryFarm13 = '';
let displayStoryQuarry = '';
let displayStoryFarm14 = '';
let displayStoryFarm15 = '';
let displayStoryFarm16 = '';
let displayStoryFarm17 = '';
let displayStoryOlives = '';

let displayStoryWarehouse0 = '';
let displayStoryWarehouse1 = '';
let displayStoryWarehouse2 = '';

let displayStoryHands0 = '';
let displayStoryHands1 = '';
let displayStoryHands2 = '';
let displayStoryHands3 = '';
let displayStoryHands4 = '';
let displayStoryHands5 = '';
let displayStoryHands6 = '';
let displayStoryHands7 = '';
let displayStoryHands8 = '';
let displayStoryHands9 = '';
let displayStoryHands10 = '';
let displayStoryHands11 = '';
let displayStoryHands12 = '';
let displayStoryHands13 = '';
let displayStoryHands14 = '';
let displayStoryHands15 = '';
let displayStoryHands16 = '';
let displayStoryHands17 = '';
let displayStoryHands18 = '';
let displayStoryHands19 = '';
let displayStoryHands20 = '';
let displayStoryHands21 = '';
let displayStoryHands22 = '';
let displayStoryHands23 = '';
let displayStoryHands24 = '';
let displayStoryHands25 = '';
let displayStoryHands26 = '';
let displayStoryHands27 = '';
let displayStoryHands28 = '';
let displayStoryHands29 = '';
let displayStoryHands30 = '';
let displayStoryHands31 = '';
let displayStoryHands32 = '';
let displayStoryHands33 = '';
let displayStoryHands34 = '';
let displayStoryHands35 = '';

let displayStoryFound = '';
let displayStoryFoundCopper = '';
let displayStoryMineScout = '';
let displayStoryMineDig = '';
let displayStoryFoundry = '';
let displayStoryTribute = '';

let displayStoryResidenceFirstVisit = '';
let displayStoryResidence00 = '';
let displayStoryResidence01 = '';
let displayStoryResidence02 = '';
let displayStoryResidence03 = '';
let displayStoryResidence04 = '';
let displayStoryResidence05 = '';
let displayStoryResidence06 = '';
let displayStoryResidence07 = '';
let displayStoryResidence08 = '';
let displayStoryResidence09 = '';
let displayStoryResidence10 = '';
let displayStoryResidence11 = '';
let displayStoryResidence12 = '';
let displayStoryResidence13 = '';

let displayStoryVillage0 = '';
let displayStoryVillage1 = '';
let displayStoryVillage2 = '';
let displayStoryVillage3 = '';
let displayStoryVillage4 = '';
let displayStoryVillage5 = '';
let displayStoryVillage6 = '';
let displayStoryVillage7 = '';
let displayStoryVillage8 = '';
let displayStoryVillage9 = '';
let displayStoryVillage10 = '';
let displayStoryVillage11 = '';
let displayStoryVillage12 = '';
let displayStoryVillage13 = '';
let displayStoryVillage14 = '';
let displayStoryVillage15 = '';
let displayStoryVillage16 = '';
let displayStoryVillage17 = '';

let displayNamePlayer = '';

let displayGoToPraediumFromRes = '';
let displayGoToResidence = '';
let displayGoToTownship = '';
let displayGoToPraedium = '';
let displayGoToPort = '';
let displayGoToTownshipFromPort = '';

let displayVillageTitle0 = '';
let displayVillageTitle1 = '';
let displayVillageTitle2 = '';
let displayVillageTitle3 = '';
let displayVillageTitle4 = '';
let displayVillageTitle5 = '';
let displayVillageTitle6 = '';

let displayCitizens = '';
let displayPilgrims = '';
let displayDemographics = '';
let displayFiat = '';
let displayTreasury = '';
let displayAsSpent = '';
let displayLifetimeRevenues = '';
let displayLifetimeCosts = '';
let displayIncome = '';
let displayPnL = '';
let displayRent = '';
let displayRealEstate = '';
let displayMarket = '';
let displayHusbandry = '';
let displayConjunction = '';
let displayTourism = '';
let displayWorship = '';
let displayTribute = '';
let displayMilitary = '';
let displayStudy = '';
let displayTaxes = '';
let displayMateriel = '';
let displayPonies = '';
let displayCavalry = '';
let displayPrayers = '';
let displayChampionships = '';
let displayChance = '';
let displayScripture = '';
let displayRelic = '';
let displayMessiahs = '';
let displayRats = '';
let displayStatistics = '';
let displayOffense = '';
let displayDefense = '';

let displayLoaves = '';
let displayOil = '';
let displayBeer = '';
let displayWine = '';
let displaySyrup = '';
let displayJuice = '';
let displayDriedFigs = '';
let displayTrinkets = '';
let displayAmountProduced = '';
let displayAmountSpent = '';

let displayConsumes = '';
let displayUsed = '';
let displayBakery = '';
let displayOliveMill = '';
let displayBrewery = '';
let displayWinery = '';
let displayKitchen = '';
let displayPress = '';
let displayGreenhouse = '';
let displayAtelier = '';

let displayForewordA = '';
let displayForewordScripture = '';
let displayForewordSource = '';
let displayForewordB = '';
let displayForewordLabel = '';

let displayNewLanguage = '';
let displayLanguageQuote = '';

let displayInfoFinal = '';
let displayInfoMadeWith = '';
let displayInfoDedication = '';
let displayInfoThanks = '';
let displayInfoScripture = '';

let displayLegalFinal = '';
let displayBoilerplate = '';
let displayLegalQuote = '';

let displayOptionsFlavourFinal = '';
let displayOptionsFlavour = '';

let displayBoxCopy = '';

let displayHeir = '';
let displayWinMessage = '— Mon ami, dit Valentine,<br>le comte ne vient-il pas de nous<br>dire que l’humaine sagesse était<br>tout entière dans ces deux mots :<br><br>— <span id="Dumas">Attendre et espérer !</span><br><br><br><br><br><span id="fin">FIN DU PRAEDIUM</span><br><br><br><br>';
let displayEndButton = '';

let displayModCodeLabel = '';
let displayModCodeTextArea = '';
let displaySubmitModCode = '';
let displayDismissMods = '';



function Translate(language, bark = true) {
    player.speaks = language;

    if (language == 'English') {
        displayGameEdition = 'GOLD EDITION';

        displayIUnderstand = 'I UNDERSTAND';
        displayOK = "I AM READY TO CONTINUE";
        displayOptions = 'Options';
        displayMusic = 'Music? (in progress 😔)';
        displaySounds = 'Sounds? (in progress 😔)';
        displayAnimations = 'Cosmetic Animations?';
        displayInStock = 'In Stock';
        displayStaff = 'Staff';
        displayFieldhands = 'Fieldhands';
        displayHireHand = 'HIRE FIELDHAND';
        displayCrop = 'Crop';
        displayAcresFarmed = 'Acres<br>Farmed';
        displayHarvested = 'Bushels<br>Harvested';
        displayHarvest = 'Harvest';
        displaySpent = 'Bushels<br>Spent';
        displayStarving = 'YOUR MEN ARE STARVING!!';
        displayStarvingHorse = 'THESE POOR ANIMALS<br>ARE STARVING!!';
        displayRatPlague = 'RAT PLAGUE!!';
        displayCentury = 'Century';
        displayDecade = 'Decade';
        displayYear = 'Year';
        displaySemester = 'Semester';
        displaySeason = 'Season';
        displayMonth = 'Month';
        displayFortnight = 'Fortnight';
        displayWeek = 'Week';
        displayDay = 'Day';
        displayLabelAvailable = 'Available';
        displayWheat = 'Wheat';
        displayBarley = 'Barley';
        displayOlive = 'Olive';
        displayDate = 'Date';
        displayFig = 'Fig';
        displayPomegranate = 'Pomegranate';
        displayGrape = 'Grape';
        displayLogs = 'Logs';
        displayBoards = 'Boards';
        displayLumberjacks = 'Lumberjacks';
        displaySawyers = 'Sawyers';
        displayStone = 'Stone';
        displayOre = 'Ore';
        displayCopper = 'Copper';
        displayVignerons = 'Vignerons';
        displayArborists = 'Arborists';
        displayHorticulturalists = 'Horticulturalists';
        displayMasons = 'Masons';
        displayMiners = 'Miners';
        displayCindermen = 'Cindermen';
        displayMetallurgists = 'Braziers';
        displayGood = 'Good';
        displayScoreProduced = 'Score<br>Produced';
        displayScoreSpent = 'Score<br>Spent';
        displayHomersProduced = 'Homers<br>Produced';
        displayHomersSpent = 'Homers<br>Spent';

        displayLabelBuyLand0 = 'LEASE ANOTHER ACRE';
        displayLabelBuyLand1 = 'LEASE A LARGER PLOT';
        displayLabelBuyLand2 = 'BUY YOUR LAND';
        displayHireAccountant = 'HIRE AN ACCOUNTANT';
        displayLabelBuyLand3 = 'BUY MORE LAND';
        displayLabelBuyLand4 = 'HAVE A FENCE ERECTED';
        displayLabelBuyLand5 = 'ACQUIRE THE NEARBY MEADOW';
        displayLabelBuyLand6 = 'DIG UP THE STUMPS';
        displayLabelBuyLand7 = 'UPROOT THE DEAD TREES';
        displayLabelBuyLand8 = 'CLEAR THE LAND';
        displayLabelBuyLand9 = 'PLANT AN OLIVE ORCHARD';
        displayLabelBuyLand10 = 'PURCHASE THE ADJACENT FARM';
        displayLabelForest = 'BUY A PRIVATE FOREST';
        displayLabelLogCamp = 'START A LOGGING CAMP';
        displayLabelSawmill = 'BUILD A SAWMILL';
        displayLabelBuyLand11 = 'UPDATE YOUR FENCE';
        displayLabelBuyLand12 = 'EXPAND YOUR TERRITORY';
        displayLabelBuyLand13 = 'FORTIFY YOUR WALLS';
        displayLabelQuarry = 'INVEST IN A STONE QUARRY';
        displayLabelBuyLand14 = 'PAVE THE ROAD TO THE PORT';
        displayLabelBuyLand15 = 'DIG A SECOND WELL';
        displayLabelBuyLand16 = 'INVEST IN A BARLEY FIELD';
        displayLabelBuyLand17 = 'PURCHASE A SUCCESSFUL FRUIT PLANTATION';

        displayLabelRentWarehouse0 = 'RENT WAREHOUSE SPACE<br>TO STORE YOUR GRAIN';
        displayLabelRentWarehouse1 = 'RENT MORE WAREHOUSE SPACE';
        displayLabelRentWarehouse2 = 'PURCHASE A WAREHOUSE';

        displayLabelWasteTime = 'RELAX AND DO NOTHING';
        displayLabelResidence00 = 'BUILD SHANTY ON YOUR OWN LAND';
        displayLabelResidence01 = 'IMPROVE YOUR SHANTY';
        displayLabelResidence02 = 'IMPROVE YOUR CABIN';
        displayLabelResidence03 = 'BUILD BAKERY';
        displayLabelResidence04 = 'BUILD OLIVE MILL';
        displayLabelResidence05 = 'IMPROVE THE MAIN HOUSE';
        displayLabelResidence06 = 'BUILD BREWERY';
        displayLabelResidence07 = 'BUILD WINERY';
        displayLabelResidence08 = 'BUILD KITCHEN';
        displayLabelResidence09 = 'BUILD PRESS';
        displayLabelResidence10 = 'BUILD GREENHOUSE';
        displayLabelResidence11 = 'IMPROVE THE ESTATE';
        displayLabelResidence12 = 'BUILD ATELIER';
        displayLabelResidence13 = 'REALLY ZHUZH THIS PLACE UP SOME, SON';

        displayLabelFound = 'FOUND A VILLAGE';
        displayLabelBuild0 = 'HIRE BLACKSMITH';
        displayLabelBuild1 = 'COMMISSION WORKSHOP';
        displayLabelBuild2 = 'ERECT TOWN HALL';
        displayLabelBuild3 = 'BUILD INSULA';
        displayLabelMineScout = 'SCOUT FOR A PROPER MINE SITE';
        displayLabelMineDig = 'DIG MINE';
        displayLabelFoundry = 'BEGIN A COPPER FOUNDRY';
        displayLabelBuild4 = 'ADD SECOND STORY';
        displayLabelBuild5 = 'BUILD MARKETPLACE';
        displayLabelBuild6 = 'ADD THIRD STORY';
        displayLabelBuild7 = 'BUILD ANOTHER INSULA';
        displayLabelBuild8 = 'ERECT SCHOOLHOUSE';
        displayLabelBuild9 = 'BUILD THIRD INSULA';
        displayLabelBuild10 = 'BUILD STABLE';
        displayLabelBuild11 = 'BUILD TEMPLE';
        displayLabelBuild12 = 'BUILD ARENA';
        displayLabelBuild13 = 'CHARTER BANK';
        displayLabelBuild14 = 'CREATE HERMETIC ORDER';
        displayLabelBuild15 = 'DIG SEWERS';
        displayLabelBuild16 = 'ERECT CITY GATES';
        displayLabelBuild17 = 'ESTABLISH MONUMENT';

        displayStoryFarm0 = 'NOW I CAN PROVIDE FOR MY FAMILY';
        displayStoryFarmMildew = 'YOU HAVE JUST RECEIVED A MESSAGE FROM THE MAN WHO RUNS THE WAREHOUSE WHERE YOU KEEP YOUR WHEAT:<div id="nasirMessage">Roof damage has let water in; mildew has claimed 90% of all grain in storage; my sincerest apologies<br>—Ea-nāṣir</div>';
        displayStoryFarm1 = 'WITH TWICE THE LAND I CAN DOUBLE MY PROFITS';
        displayStoryFarm2 = 'THERE ARE MEN IN NEED OF WORK';
        displayStoryAccountant = 'I HAVE NO HEAD FOR FIGURES AT ALL';
        displayStoryFarm3 = 'REINVESTING OUR PROFIT MEANS WE CAN GROW';
        displayStoryFarm4 = '“THE ONLY FENCE AGAINST THE WORLD IS A THOROUGH KNOWLEDGE OF IT”<br>—JOHN LOCKE';
        displayStoryFarm5 = 'PLENTY OF ROOM FOR SOME TREES';
        displayStoryFarm6 = '“MAN’S TRUE TAPROOTS ARE NOURISHED IN THE SEQUENCE OF GENERATIONS”<br>—ERIK H. ERIKSON';
        displayStoryFarm7 = 'I’VE SEEN MORE THAN<br>I SHOULD HAVE TO<br>I’VE SEEN THIS<br>ON MY OWN<br>—TAPROOT';
        displayStoryFarm8 = 'IF YOU WANT SOMETHING DONE RIGHT YOU’VE GOT TO DO IT YOURSELF';
        displayStoryFarm9 = '“HE PLANTS HIS TREES TO SERVE A RACE TO COME”<br>—STATIUS';
        displayStoryFarm10 = 'IF IT WASN’T HIM IT WOULD BE ME';
        displayStoryForest = '“HEAVEN IS UNDER OUR FEET AS WELL AS OVER OUR HEADS”<br>—HENRY DAVID THOREAU';
        displayStoryLoggingCamp = 'WELL YOU WORK IN THE WOODS<br>FROM MORNING TO NIGHT<br>YOU LAUGH AND SING<br>AND YOU CUSS AND FIGHT<br>ON SATURDAY NIGHT<br>YOU GO TO EUGENE<br>AND ON A SUNDAY MORNING<br>YOUR POCKETS ARE CLEAN<br>—LEON PAYNE';
        displayStorySawmill = '“WOOD IS THE MOST HUMANLY INTIMATE OF ALL MATERIALS. IT IS UNIVERSALLY BEAUTIFUL TO MAN”<br>—FRANK LLOYD WRIGHT';
        displayStoryFarm11 = 'GOOD FENCES MAKE GOOD NEIGHBOURS';
        displayStoryFarm12 = 'BRING ME MEN<br>TO MATCH MY MOUNTAINS,<br>BRING ME MEN<br>TO MATCH MY PLAINS,<br>MEN WITH EMPIRES<br>IN THEIR PURPOSE,<br>AND NEW ERAS<br>IN THEIR BRAINS<br>—SAM WALTER FOSS';
        displayStoryFarm13 = 'THIS WILL KEEP OUT THE WOLVES';
        displayStoryQuarry = '“A PILE OF ROCKS CEASES TO BE A PILE OF ROCKS THE MOMENT A MAN CONTEMPLATES IT WITH THE IDEA OF A CATHEDRAL IN HIS MIND”<br>—ANTOINE DE SAINT-EXUPÉRY';
        displayStoryFarm14 = 'TO NONE IS IT PERMITTED TO MUTTER SACRED VERSES BEFORE THE PUBLIC GAZE AS HE WALKETH IN THE STREET OR MARKETPLACE<br><br>A SYNOPSIS AND CODIFICATION OF THE LAWS AND ORDINANCES OF THE KITÁB-I-AQDAS IV.D.1.Y.XXIX';
        displayStoryFarm15 = '“THE TIME TO DIG A WELL IS BEFORE YOU ARE THIRSTY”<br>—ZHU XI<br><br>(Per Harvest Yield Minimum +25%)';
        displayStoryFarm16 = 'HARD TO BELIEVE ALL THIS BEGAN WITH JUST A SINGLE PATCH OF EARTH ' + year + ' YEARS AGO. HONESTLY IT’S DIFFICULT TO EVEN REMEMBER WHAT LIFE WAS LIKE BACK THEN';
        displayStoryFarm17 = 'THE PREVIOUS OWNER GUARANTEES ITS PROFITABILITY. I AM TOLD DATES WILL BE READY AT THE END OF EVERY SUMMER, AND FIGS IN THE LATE SPRING. POMEGRANATES WILL BE READY IN EARLY WINTER, THEN GRAPES SHOULD COME ALONG A FEW WEEKS LATER, BUT THEY ARE FICKLE';
        displayStoryOlives = 'IT HAS BEEN EIGHT LONG YEARS SINCE YOU PLANTED YOUR OLIVE ORCHARD. FINALLY THE TREES ARE MATURE, EVERY BRANCH LADEN WITH RIPE FRUIT. AND THEY SHOULD COME IN AROUND THE SAME TIME EVERY YEAR FROM NOW ON';

        displayStoryWarehouse0 = 'THIS PLACE COMES HIGHLY RECOMMENDED';
        displayStoryWarehouse1 = '“WHAT IS COMMON TO THE GREATEST NUMBER RECEIVES THE LEAST AMOUNT OF CARE”<br>—ARISTOTLE';
        displayStoryWarehouse2 = '“WHILST, IN THE MAJORITY OF MEN, THERE IS SUCH A LOVE OF TRIED ARRANGEMENTS, AND SO GREAT A DREAD OF EXPERIMENTS, THAT THEY WILL PROBABLY NOT ACT UPON THIS RIGHT UNTIL LONG AFTER IT IS SAFE TO DO SO”<br>—HERBERT SPENCER';

        displayStoryHands0 = 'YOU HAVE BROUGHT ON YOUR FIRST MAN. HIS NAME IS JOHN';
        displayStoryHands1 = 'JOHN HAS A BROTHER LOOKING FOR WORK. YOU COULD USE ANOTHER GOOD MAN';
        displayStoryHands2 = 'WE CAN AFFORD A NEW MAN. THE BROTHERS SUGGEST A CLOSE FRIEND';
        displayStoryHands3 = 'YOU BRING ON ANOTHER MAN SUGGESTED BY THE BROTHERS';
        displayStoryHands4 = 'TIME TO HIRE AGAIN. YOU PUT OUT THE WORD AND TAKE ON ANOTHER MAN';
        displayStoryHands5 = 'MANY HANDS MAKE LIGHT WORK, AS THEY SAY';
        displayStoryHands6 = 'NOW THAT YOU OWN HIS PROPERTY, YOUR NEIGHBOUR ASKS IF HE CAN STAY ON AND WORK FOR YOU';
        displayStoryHands7 = 'YOUR NEIGHBOUR’S SONS HAVE STRONG BACKS AND ARE READY TO WORK. YOU HIRE THE ELDEST';
        displayStoryHands8 = 'YOU TAKE ON YOUR NEIGHBOUR’S MIDDLE BOY';
        displayStoryHands9 = 'THE NEIGHBOUR’S YOUNGEST IS READY TO JOIN';
        displayStoryHands10 = 'JOHN KNOWS OF GOOD MEN. HE BRINGS IN ANOTHER';
        displayStoryHands11 = 'YOUR NEIGHBOUR HAS A BROTHER-IN-LAW LOOKING FOR WORK. HE BRINGS HIM TO YOU';
        displayStoryHands12 = 'EVERYONE KNOWS YOU ARE WHO TO SEE FOR WORK. A GROUP FORMS AT YOUR GATE. YOU PICK THE TALLEST MAN FROM THE CROWD';
        displayStoryHands13 = 'YOU SEE ANOTHER WHO LOOKS STRONG AND TELL HIM TO COME INSIDE';
        displayStoryHands14 = 'A SMALL MAN APPROACHES YOU. HE SAYS HE MAY NOT LOOK LIKE MUCH BUT HE IS TENACIOUS. YOU ADD HIM TO THE ROSTER';
        displayStoryHands15 = 'SO MANY WORLDS AND LANDS FOR WORKING OUT KARMA. SO VERY MANY LESSONS TO BE LEARNED!<br><br>GURU GRANTH SAHIB, ANG 7';
        displayStoryHands16 = 'PLENTY STILL TO CHOOSE FROM. YOU LET ANOTHER STRONG-LOOKING FELLOW THROUGH THE GATE';
        displayStoryHands17 = 'AS YOU SELECT THE NEXT HIRE FROM THE WAITING CROWD, ONE OF YOUR MEN BRINGS NEWS: JOHN TOOK ILL WITH A FEVER LAST NIGHT AND DIDN’T WAKE UP THIS MORNING. A SHAME. TO REPLACE HIM YOU LET IN ONE MORE';
        displayStoryHands18 = 'JOHN’S BROTHER IS SICK WITH GRIEF AND CAN NOT WORK. HE’LL NEED TO BE REPLACED AS WELL UNFORTUNATELY. YOU PICK TWO MORE FROM THE CROWD';
        displayStoryHands19 = 'MORE PEOPLE HERE THAN WE HAVE ROOM FOR, BUT WE DO NEED ONE MORE';
        displayStoryHands20 = 'SLAVES, ALWAYS OBEY YOUR EARTHLY MASTERS IN EVERY WAY, NOT ONLY WHEN THEY ARE WATCHING YOU, BUT ALL THE TIME, FEARING THE LORD<br><br>COLOSSIANS 3:22';
        displayStoryHands21 = 'EVERY DAY SOMEONE ASKS: ARE YOU HIRING? WELL, TODAY WE ARE. YOU TAKE ON A NEW MAN INTRODUCED TO YOU BY ONE OF YOUR FARMHANDS';
        displayStoryHands22 = 'SOMETIMES YOU JUST CAN’T HELP BUT LOATHE ALL THESE GODDAM PEOPLE';
        displayStoryHands23 = 'WELL, THERE IS ALWAYS MORE WORK TO BE DONE, AND IT WILL NOT DO ITSELF';
        displayStoryHands24 = 'NEW FELLOW STARTS TODAY. LOOKS PRETTY YOUNG, BUT HE SEEMS EAGER';
        displayStoryHands25 = 'THE NEW BOY LOST A HAND IN AN ACCIDENT JUST HOURS AFTER HIS FIRST DAY BEGAN. A TRAGEDY FOR HIS FAMILY, SURELY. WELL, THE LORD GIVETH AND THE LORD TAKETH AWAY, AS JOB TELLS US. YOU HIRE TWO MORE INSTEAD OF ONLY ONE';
        displayStoryHands26 = 'DEAR LORD, THAT POOR BOY. HARD TO GET THE SIGHT OF ALL THAT BLOOD OUT OF YOUR MIND';
        displayStoryHands27 = 'UNEASY LIES THE HEAD THAT WEARS A CROWN<br><br>THE SECOND PART OF HENRIE THE FOURTH 3.1.1735';
        displayStoryHands28 = 'THE MEN WHO HAVE BEEN TENDING WHAT IS NOW YOUR BARLEY FIELD SHOW UP FOR WORK THE NEXT MORNING, HOPEFUL TO JOIN YOUR STAFF AND KEEP THEIR JOBS. THEIR LEADER STEPS FORWARD AND YOU WELCOME HIM TO HIS NEW LIFE, VERY SIMILAR TO HIS LAST ONE';
        displayStoryHands29 = 'THE NEXT MAN SILENTLY COMES THROUGH THE GATE AND BEGINS WORK AS IF NOTHING AT ALL HAD CHANGED. WELL... YOU SUPPOSE, TO HIM, NOT MUCH HAS';
        displayStoryHands30 = 'THIS NEXT FELLOW SEEMS LIKE A LITTLE BIT OF A ROUGH CUSTOMER, BUT, HE ALSO LOOKS LIKE HE’S BEEN WORKING GRAIN HIS WHOLE LIFE. PROBABLY A GOOD MAN TO HAVE ON THE TEAM';
        displayStoryHands31 = 'GOOD LORD, THIS IS TAKING ALL DAY. YES, YES, COME IN, COME IN, GENTLEMEN';
        displayStoryHands32 = 'SOME OF THESE BOYS LOOK LIKE THEY COULD SURE USE A GOOD MEAL';
        displayStoryHands33 = 'SO MANY OF THE MEN IN THIS REGION RELY ON YOU NOW FOR A LIVELIHOOD; THE MEN *AND* THEIR FAMILIES';
        displayStoryHands34 = 'I’LL STAND BY ALL THIS DRINKING<br>IF IT HELPS ME THROUGH THESE DAYS<br>—INTERPOL';
        displayStoryHands35 = 'CONGRATULATIONS. YOU EMPLOY ALL YOU KNOW';

        displayStoryFound = '“I HAVE SONS, I HAVE WEALTH,” WITH SUCH THOUGHTS THE FOOL IS TORMENTED. BUT IF ONE’S SELF IS NOT EVEN ONE’S OWN, HOW THEN ARE SONS? HOW THEN IS WEALTH?<br><br>DHAMMAPADA 5.62';
        displayStoryFoundCopper = 'A PAIR OF HIKERS IN YOUR MOUNTAINS HAVE DISCOVERED NUGGETS OF WHAT APPEARS TO BE ORICHALCUM!';
        displayStoryMineScout = 'YOUR SCOUTS FOUND A RICH VEIN IN YOUR EASTERN FOOTHILLS';
        displayStoryMineDig = 'MINERALS HAVE THEIR OWN LIFE JUST AS VEGETABLES DO, AND ANIMALS AND BIRDS, AND HUMANS<br><br>PHÁP CHÁNH TRUYỀN, PART 5';
        displayStoryFoundry = '“THE ‘HOLOCENE’ HAS ENDED. THE GARDEN OF EDEN IS NO MORE. WE HAVE CHANGED THE WORLD SO MUCH THAT SCIENTISTS SAY WE ARE IN A NEW GEOLOGICAL AGE: THE ‘ANTHROPOCENE’. THE AGE OF MAN. WE MUST MOVE BEYOND GUILT OR BLAME, AND GET ON WITH THE PRACTICAL TASKS AT HAND”<br>—SIR DAVID FREDERICK ATTENBOROUGH';
        displayStoryTribute = 'THE LOCAL WARLORD KING HAS CAUGHT WIND OF YOUR SUCCESS AT LAST. QUOTH HIS EMISSARY: “OF COURSE, TARIFFS MUST BE LEVIED”';

        displayStoryResidenceFirstVisit = 'THERE’S NO PLACE LIKE HOME: YOUR CAMPSITE, ANONYMOUS AMONG THE HUNDREDS OF OTHERS JUST LIKE IT ALL NESTLED HERE, IN THIS NARROW, ARID VALLEY, WHERE YOU RENT THIS PATCH OF DIRT FOR AN EXORBITANT RATE';
        displayStoryResidence00 = 'LIVING ON MY OWN LAND WILL CERTAINLY MAKE IT EASY TO GET TO WORK IN THE MORNING';
        displayStoryResidence01 = 'FINALLY SOME SPACE TO STRETCH OUT MY LEGS';
        displayStoryResidence02 = 'MORE THAN ENOUGH ACREAGE IN THIS PRAIRIE FOR A MODEST HOMESTEAD, I RECKON';
        displayStoryResidence03 = 'GIVE US THIS DAY OUR DAILY BREAD<br>~STEVIE BREADSMAN<br><br>(Laborers Will Accept ' + loavesPaymentAmount + '<span class="icon Loaves inlineIcon"></span>/Week)';
        displayStoryResidence04 = '';
        displayStoryResidence05 = '';
        displayStoryResidence06 = '';
        displayStoryResidence07 = '';
        displayStoryResidence08 = '';
        displayStoryResidence09 = '';
        displayStoryResidence10 = '';
        displayStoryResidence11 = '';
        displayStoryResidence12 = '';
        displayStoryResidence13 = '';

        displayStoryVillage0 = 'HE WILL NEED LUMBER FOR THE FORGE';
        displayStoryVillage1 = 'NOW WE CAN BUILD';
        displayStoryVillage2 = 'WE’VE GOT TO HAVE SOME LAW AND ORDER';
        displayStoryVillage3 = 'PEOPLE NEED HOMES';
        displayStoryVillage4 = 'MORE APARTMENTS MEAN MORE TENANTS, MORE TENANTS MEAN MORE RENT';
        displayStoryVillage5 = 'THE SPICES OF THE MARKET ARE FRAGRANT INDEED';
        displayStoryVillage6 = 'THE BUILDERS ASSURE THERE IS NO DANGER';
        displayStoryVillage7 = 'CITIZENS FLOW IN FROM THE COUNTRYSIDE NOW, SEEKING OPPORTUNITY';
        displayStoryVillage8 = '“TEACH A MAN TO FISH AND YOU FEED HIM FOR A LIFETIME”<br>—MAIMONIDES<br><br>(Per Harvest Yield Maximum +33%)';
        displayStoryVillage9 = 'LIVE IN A GOOD PLACE<br><br>TAO TE CHING 8:5';
        displayStoryVillage10 = 'HORSES DRIVE PROGRESS';
        displayStoryVillage11 = 'THE TRUE SERVANTS OF GOD ARE THOSE WHO WALK UPON THE EARTH EASILY, AND WHEN THE IGNORANT ADDRESS THEM HARSHLY, THEY REPLY WITH WORDS OF PEACE<br><br>AL-FURQAN 63';
        displayStoryVillage12 = '“THEY DESIRE JUST TWO THINGS, BREAD AND CIRCUSES”<br>—JUVENAL';
        displayStoryVillage13 = '“TO CONTRACT NEW DEBTS IS NOT THE WAY TO PAY OLD ONES”<br>—GEORGE WASHINGTON';
        displayStoryVillage14 = 'YOU HAVE THE RIGHT TO LABOUR, BUT YOU HAVE NO RIGHT TO THE FRUITS OF YOUR LABOURS. NEVER BELIEVE YOU ARE THE CAUSE OF THE RESULTS OF YOUR CHOICES. WORK HARD AND BE EVEN-TEMPERED IN SUCCESS AND FAILURE. ... THOSE WHO SEEK TO ENJOY THE FRUITS OF THEIR WORKS ARE MISERABLE.<br><br>BHAGAVAD GITA 2.47-49';
        displayStoryVillage15 = 'CLEANLINESS IS GODLINESS';
        displayStoryVillage16 = 'THEY HATE HIM WHO REPROVES IN THE GATE, AND THEY ABHOR HIM WHO SPEAKS THE TRUTH<br><br>AMOS 5:10';
        displayStoryVillage17 = 'THE BRONZE PLAQUE ON THE PINK MARBLE BASE READS:<br><br>≈ THE 8 VIRTUES ≈<br><br>♠<br>• HONESTY •<br>TELL THE TRUTH<br>♠<br>• HONOR •<br>DO WHAT IS RIGHT<br>♠<br>• VALOR •<br>STAND AGAINST INJUSTICE<br>♠<br>• SACRIFICE •<br>SHARE YOUR BLESSINGS<br>♠<br>• COMPASSION •<br>BE KIND TO THE WEAK<br>♠<br>• JUSTICE •<br>BE FAIR TO ALL<br>♠<br>• SPIRITUALITY •<br>LISTEN TO THE LIGHT<br>♠<br>• HUMILITY •<br>RESIST PRIDE<br>♣';

        displayNamePlayer = '“What is your name, citizen?”';

        displayGoToPraediumFromRes = 'GO BACK TO YOUR LANDS →';
        displayGoToResidence = '← GO TO YOUR RESIDENCE';
        displayGoToTownship = 'GO TO TOWNSHIP →';
        displayGoToPraedium = '← RETURN TO YOUR PRAEDIUM';
        displayGoToPort = 'TRAVEL TO THE PORT →';
        displayGoToTownshipFromPort = '← RETURN TO YOUR PROVINCE';

        displayVillageTitle0 = 'The Settlement of';
        displayVillageTitle1 = 'The Outpost of';
        displayVillageTitle2 = 'The Hamlet of';
        displayVillageTitle3 = 'The Village of';
        displayVillageTitle4 = 'The Town of';
        displayVillageTitle5 = 'The City of';
        displayVillageTitle6 = 'The Capital of';

        displayCitizens = 'Citizens';
        displayPilgrims = 'Pilgrims';
        displayDemographics = 'Demographics';
        displayFiat = 'Fiat';
        displayTreasury = 'Treasury';
        displayAsSpent = 'Spent';
        displayLifetimeRevenues = 'Lifetime Revenues';
        displayLifetimeCosts = 'Lifetime Costs';
        displayIncome = 'Income';
        displayPnL = 'Profit & Loss';
        displayRent = 'Rent';
        displayRealEstate = 'Real Estate';
        displayMarket = 'Retail';
        displayHusbandry = 'Husbandry';
        displayConjunction = 'Conjunction';
        displayTourism = 'Tourism';
        displayWorship = 'Worship';
        displayTribute = 'Tribute';
        displayMilitary = 'Military';
        displayStudy = 'Study';
        displayTaxes = 'Taxes';
        displayMateriel = 'Materiel';
        displayPonies = 'Ponies';
        displayCavalry = 'Cavalry';
        displayPrayers = 'Prayers';
        displayChampionships = 'Championships';
        displayChance = 'chance';
        displayScripture = 'Scripture';
        displayRelic = 'Artifacts';
        displayMessiahs = 'Messiahs';
        displayRats = 'Rats';
        displayStatistics = 'Statistics';
        displayOffense = 'OFF';
        displayDefense = 'DEF';

        displayLoaves = 'Loaves';
        displayOil = 'Oil';
        displayBeer = 'Beer';
        displayWine = 'Wine';
        displaySyrup = 'Syrup';
        displayJuice = 'Juice';
        displayDriedFigs = 'Sun-Dried Figs';
        displayTrinkets = 'Trinkets';
        displayAmountProduced = 'Units<br>Produced';
        displayAmountSpent = 'Units<br>Spent';

        displayConsumes = 'Consumes';
        displayUsed = 'Used';
        displayBakery = 'Bakery';
        displayOliveMill = 'Olive Mill';
        displayBrewery = 'Brewery';
        displayWinery = 'Winery';
        displayKitchen = 'Kitchen';
        displayPress = 'Press';
        displayGreenhouse = 'Greenhouse';
        displayAtelier = 'Atelier';

        displayForewordA = 'The year is 200 B.C. and thou art a humble Tartessian sharecropper eking out a modest living under the brutal Mediterranean sun in Palestinian Galilee. From dawn to dusk dost thou work the chalky, unforgiving soil with nothing but thine own calloused hands and a sharp stick.';
        displayForewordScripture = '“O Maker of the material world, thou Holy One! How far from the fire? How far from the water? How far from the consecrated bundles of baresma? How far from the faithful?”';
        displayForewordSource = 'Vendidad 8:6';
        displayForewordB = 'Hast thou what it takes to pen the constitution of a city-state that will light the way for centuries while personally achieving transcendent enlightenment and absolution from a lifetime of sins? Now is thy chance!';
        displayForewordLabel = 'I AM READY TO BEGIN';

        displayNewLanguage = 'The current language is now set to English.';
        displayLanguageQuote = '<div id="divSystemMessageScripture">“There is no true knowledge without right faith, no virtuous conduct is possible without knowledge, without virtue there is no liberation, and without liberation, no nirvana.”</div><div id="divSystemMessageSource">Uttaradhyayana 28:30</div>';

        displayInfoMadeWith = 'For Dylan, DJ, Simone, Carlos, and Gustavo. I love y’all so much.<br><br>Made with CodePen, the GNU Image Manipulation Program, GitHub, Inkscape and Visual Studio Code.';
        displayInfoDedication = 'Dedicated to Lori and Corey Cole, Jeff and ’Manda Dee, Richard Garriott, ALexis JAnson, Chris “Pumaman” Jones, Denis Loubet, David “aniwey” L., Tom Rothamel, Tim Sweeney and Michael Townsend, and in loving memory of Travontee’ Flemming, Francisco Furlan, La’Voris McKeever and Philip J Reed, VSc. I really, really wish you guys were here.';
        displayInfoThanks = 'Special thanks to Mohammad Alavi, Sheila Bailey, Todd T. Brannon, Dave and Anna Davis, Miguel Angel Droz III, Derek Evans, Kenneth Garagnon, Sean Glavin, Hayley Hackett, Marty Hirsch, Leif and Marisol Johansen, David Macaulay, the Méndez family, Brian Moran, Flathead Mike Niles, Jim Shepperd, Grant Sutherland, Benjamin A. Taylor and W3Schools.';
        displayInfoScripture = '<div id="divSystemMessageScripture">“If you hear the Way one morning and die that night, you die content.”</div><div id="divSystemMessageSource">Analects 4:8</div>';

        displayBoilerplate = 'THIS SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND.';
        displayLegalQuote = '<div id="divSystemMessageScripture">“I enjoin you to safeguard your fellow men.”</div><div id="divSystemMessageSource">—Ḥamza ibn ‘Alī ibn ʾAḥmad</div>';

        displayOptionsFlavour = '“Anxiety is the dizziness of freedom.”<div id="divOptionsSource">—Søren Kierkegaard</div>';

        displayBoxCopy = 'Step into the thonged sandals of a simple Tartessian grain farmer in the year 200 BC. Dost thou have what it takes to pen the constitution of a city-state that will light the way for centuries and personally achieve transcendent enlightenment, milord??<br><br>Be literally transported to ancient Roman times by this cutting edge computer simulation that puts YOU in the heart of the pulse-pumping REAL FARMING ACTION!';

        displayHeir = 'CHOOSE AN HEIR';
        displayEndButton = 'THE END';

        displayModCodeLabel = '<i>USER DISCRETION IS STRONGLY ADVISED!</i><br>Do not copy any code into this window that you do not absolutely understand and/or trust!';
        displayModCodeTextArea = 'Paste your modCode here';
        displaySubmitModCode = 'SUBMIT MODCODE';
        displayDismissMods = 'I AM FINISHED HERE';
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////

    else if (language == 'Spanish') {
        displayGameEdition = 'EDICIÓN DE ORO';

        displayIUnderstand = 'ENTIENDO';
        displayOK = "ESTOY LISTO<br>PARA CONTINUAR";
        displayOptions = 'Opciones';
        displayMusic = '¿Música? (en proceso 🙄)';
        displaySounds = '¿Sonidos? (en proceso 🙄)';
        displayAnimations = '¿Animaciones cosméticas?';
        displayInStock = 'En Stock';
        displayStaff = 'Personal';
        displayFieldhands = 'Labriegos';
        displayHireHand = 'CONTRATAR LABRIEGO';
        displayCrop = 'Cultivo';
        displayAcresFarmed = 'Aranzadas<br>Cultivadas';
        displayHarvested = 'Fanegas<br>Cosechadas';
        displayHarvest = 'Cosecha';
        displaySpent = 'Fanegas<br>Gastadas';
        displayStarving = '¡¡TUS HOMBRES SE<br>MUEREN DE HAMBRE!!';
        displayStarvingHorse = '¡¡ESTOS POBRES<br>ANIMALES SE<br>ESTÁN MURIENDO<br>DE HAMBRE!!';
        displayRatPlague = '¡¡PESTE RATA!!';
        displayCentury = 'Siglo';
        displayDecade = 'Década';
        displayYear = 'Año';
        displaySemester = 'Semestre';
        displaySeason = 'Estación';
        displayMonth = 'Mes';
        displayFortnight = 'Quincena';
        displayWeek = 'Semana';
        displayDay = 'Día';
        displayLabelAvailable = 'Disponible';
        displayWheat = 'Trigo';
        displayBarley = 'Cebada';
        displayOlive = 'Oliva';
        displayDate = 'Dátil';
        displayFig = 'Higo';
        displayPomegranate = 'Granada';
        displayGrape = 'Uva';
        displayLogs = 'Troncos';
        displayBoards = 'Tablas';
        displayLumberjacks = 'Leñadores';
        displaySawyers = 'Aserradores';
        displayStone = 'Piedra';
        displayOre = 'Mineral';
        displayCopper = 'Cobre';
        displayVignerons = 'Viticultores';
        displayArborists = 'Arboristas';
        displayHorticulturalists = 'Horticultores';
        displayMasons = 'Masones';
        displayMiners = 'Mineros';
        displayCindermen = 'Forjadores';
        displayMetallurgists = 'Broncistas'; // Metalúrgicos
        displayGood = 'Bien';
        displayScoreProduced = 'Veintenas<br>Producidas';
        displayScoreSpent = 'Veintenas<br>Gastadas';
        displayHomersProduced = 'Homeres<br>Producidos';
        displayHomersSpent = 'Homeres<br>Gastados';

        displayLabelBuyLand0 = 'ARRENDAR OTRO ARANZADA';
        displayLabelBuyLand1 = 'ARRENDAR UNA PARCELA MÁS GRANDE';
        displayLabelBuyLand2 = 'COMPRAR TU TERRENO';
        displayHireAccountant = 'CONTRATAR UN CONTADOR';
        displayLabelBuyLand3 = 'COMPRAR MÁS TERRENO';
        displayLabelBuyLand4 = 'HACER ELEVAR UNA CERCA';
        displayLabelBuyLand5 = 'ADQUIRIR EL PRADO CERCANO';
        displayLabelBuyLand6 = 'DESENTERRAR LOS TOCONES';
        displayLabelBuyLand7 = 'ARRANCAR LOS ÁRBOLES MUERTOS';
        displayLabelBuyLand8 = 'ARRASAR LA TIERRA';
        displayLabelBuyLand9 = 'PLANTAR UN OLIVAR';
        displayLabelBuyLand10 = 'COMPRAR LA FINCA ADYACENTE';
        displayLabelForest = 'COMPRAR UN BOSQUE PRIVADO';
        displayLabelLogCamp = 'COMENZAR UN CAMPAMENTO MADERERO';
        displayLabelSawmill = 'CONSTRUIR UN ASERRADERO';
        displayLabelBuyLand11 = 'ACTUALIZAR TU CERCA';
        displayLabelBuyLand12 = 'AMPLIAR TU TERRITORIO';
        displayLabelQuarry = 'INVERTIR EN UNA CANTERA DE PIEDRA';
        displayLabelBuyLand13 = 'FORTALECER TUS MUROS';
        displayLabelBuyLand14 = 'PAVIMENTAR EL CAMINO AL PUERTO';
        displayLabelBuyLand15 = 'EXCAVAR UN SEGUNDO POZO';
        displayLabelBuyLand16 = 'INVERTIR EN UN CAMPO DE CEBADA';
        displayLabelBuyLand17 = 'COMPRAR UN HUERTO DE FRUTAS EXITOSO';

        displayLabelRentWarehouse0 = 'ALQUILAR ESPACIO DE ALMACÉN<br>PARA ALMACENAR SU GRANO';
        displayLabelRentWarehouse1 = 'ALQUILAR MÁS ESPACIO DE ALMACÉN';
        displayLabelRentWarehouse2 = 'COMPRAR UN ALMACÉN';

        displayLabelWasteTime = 'RELAJARSE Y NO HACER NADA';
        displayLabelResidence00 = 'CONSTRUIR UNA CHOZA EN TU PROPIO TERRENO';
        displayLabelResidence01 = 'MEJORAR TU CHOZA';
        displayLabelResidence02 = 'MEJORAR TU CABAÑA';
        displayLabelResidence03 = 'CONSTRUIR UNA PANADERÍA';
        displayLabelResidence04 = 'CONSTRUIR UN ALMAZARA';
        displayLabelResidence05 = 'MEJORAR LA CASA PRINCIPAL';
        displayLabelResidence06 = 'CONSTRUIR CERVECERÍA';
        displayLabelResidence07 = 'CONSTRUIR LAGAR';
        displayLabelResidence08 = 'CONSTRUIR COCINA';
        displayLabelResidence09 = 'CONSTRUIR EXPRIMIDOR';
        displayLabelResidence10 = 'CONSTRUIR INVERNADERO';
        displayLabelResidence11 = 'MEJORAR LA FINCA';
        displayLabelResidence12 = 'CONSTRUIR ATELIER';
        displayLabelResidence13 = 'REALMENTE ZHUZH ESTE LUGAR MEJORÓ, HIJO';

        displayLabelFound = 'COMENZAR UN PUEBLO';
        displayLabelBuild0 = 'CONTRATAR HERRERO';
        displayLabelBuild1 = 'CONSTRUIR UN TALLER';
        displayLabelBuild2 = 'CONSTRUIR AYUNTAMIENTO';
        displayLabelBuild3 = 'CONSTRUIR INSULA';
        displayLabelMineScout = 'BUSCAR UN SITIO MINO ADECUADO';
        displayLabelMineDig = 'CAVAR MINA';
        displayLabelFoundry = 'COMENZAR UNA FUNDICIÓN DE COBRE';
        displayLabelBuild4 = 'AÑADIR SEGUNDO PISO';
        displayLabelBuild5 = 'CONSTRUIR MERCADO';
        displayLabelBuild6 = 'AÑADIR TERCER PISO';
        displayLabelBuild7 = 'CONSTRUIR OTRA INSULA';
        displayLabelBuild8 = 'CONSTRUIR ESCUELA';
        displayLabelBuild9 = 'CONSTRUIR TERCERA INSULA';
        displayLabelBuild10 = 'CONSTRUIR CABALLERIZA';
        displayLabelBuild11 = 'CONSTRUIR TEMPLO';
        displayLabelBuild12 = 'CONSTRUIR ARENA';
        displayLabelBuild13 = 'CONSTITUIR BANCO';
        displayLabelBuild14 = 'CREAR ORDEN HERMÉTICO';
        displayLabelBuild15 = 'EXCAVAR ALCANTARILLAS';
        displayLabelBuild16 = 'LEVANTAR PUERTAS DE LA CIUDAD';
        displayLabelBuild17 = 'ESTABLECER MONUMENTO';

        displayStoryFarm0 = 'AHORA PUEDO PROVEER PARA MI FAMILIA';
        displayStoryFarmMildew = 'ACABAS DE RECIBIR UN MENSAJE DEL HOMBRE QUE DIRIGIE EL ALMACÉN DONDE GUARDAS TU TRIGO:<div id="nasirMessage">Los daños en el techo ha dejado entrar agua; el moho ha reclamado el 90% de todo el grano almacenado; mis más sinceras disculpas<br>—Ea-nāṣir</div>';
        displayStoryFarm1 = 'CON EL DOBLE DE TERRENO PUEDO DUPLICAR MIS GANANCIAS';
        displayStoryFarm2 = 'HAY HOMBRES QUE NECESITAN TRABAJO';
        displayStoryAccountant = 'NO TENGO CABEZA PARA LAS CIFRAS EN ABSOLUTO';
        displayStoryFarm3 = 'REINVESTIR NUESTROS GANANCIAS SIGNIFICA QUE PODEMOS CRECER';
        displayStoryFarm4 = '«LA ÚNICA VALLA CONTRA EL MUNDO ES UN CONOCIMIENTO PROFUNDO DE ÉL»<br>—JOHN LOCKE';
        displayStoryFarm5 = 'MUCHO ESPACIO PARA ALGUNOS ÁRBOLES';
        displayStoryFarm6 = '«LAS VERDADERAS RAÍCES PRINCIPALES DEL HOMBRE SE NUTRE EN LA SECUENCIA DE GENERACIONES»<br>—ERIK H. ERIKSON';
        displayStoryFarm7 = 'HE VISTO MÁS DE<br>LO QUE DEBÍA TENER<br>LO HE VISTO<br>POR MI CUENTA<br>—TAPROOT';
        displayStoryFarm8 = 'SI QUIERES QUE ALGO SE HAGA BIEN TIENES QUE HACERLO TÚ MISMO';
        displayStoryFarm9 = '«EL PLANTA SUS ÁRBOLES PARA SERVIR A UNA RAZA POR VENIR»<br>—ESTACIO';
        displayStoryFarm10 = 'SI NO FUERA ÉL SERÍA YO';
        displayStoryForest = '«CIELO ESTÁ BAJO NUESTROS PIES ADEMÁS SOBRE NUESTRAS CABEZAS»<br>—HENRY DAVID THOREAU';
        displayStoryLoggingCamp = 'BUENO TRABAJAS EN EL BOSQUE<br>DE LA MAÑANA A LA NOCHE<br>TÚ RÍES Y CANTAS<br>Y TÚ MALDICES Y PELEAS<br>EL SÁBADO POR LA NOCHE<br>VAS A EUGENE<br>Y UN DOMINGO POR LA MAÑANA<br>TUS BOLSILLOS ESTÁN LIMPIOS<br>—LEON PAYNE';
        displayStorySawmill = '«MADERA ES EL MÁS HUMANAMENTE ÍNTIMO DE TODOS LOS MATERIALES. ES UNIVERSALMENTE HERMOSO PARA HUMANIDAD»<br>—FRANK LLOYD WRIGHT';
        displayStoryFarm11 = 'LAS BUENAS CERCA HACEN BUENOS VECINOS';
        displayStoryFarm12 = 'TRÁEME HOMBRES<br>PARA IGUALAR A MIS MONTAÑAS,<br>TRÁEME HOMBRES<br>PARA IGUALAR MIS LLANURAS,<br>HOMBRES QUE DESEAN<br>INICIAR IMPERIOS,<br>HOMBRES QUE SUEÑAN<br>CON NUEVAS ERA<br>—SAM WALTER FOSS';
        displayStoryFarm13 = 'ESTO MANTENDRÁ FUERA A LOS LOBOS';
        displayStoryQuarry = '«UN MONTÓN DE ROCAS DEJA DE SER UN MONTÓN DE ROCAS EN EL MOMENTO EN QUE UN HOMBRE LO CONTEMPLA CON LA IDEA DE UNA CATEDRAL EN SU MENTE»<br>—ANTOINE DE SAINT-EXUPÉRY';
        displayStoryFarm14 = 'A NINGUNO ESTÁ PERMITIDO MURTAR VERSOS SAGRADOS FRENTE AL PÚBLICO MIENTRAS CAMINA POR LA CALLE O MERCADO<br><br>UNA SINOPSIS Y CODIFICACIÓN DE LAS LEYES Y ORDENANZAS DEL KITÁB-I-AQDAS IV.D.1.Y.XXIX';
        displayStoryFarm15 = '«EL MOMENTO DE CAVAR UN POZO ES ANTES DE TENER SED»<br>—ZHU XI<br><br>(Rendimiento Mínimo Por Cosecha +25%)';
        displayStoryFarm16 = 'DIFÍCIL DE CREER QUE TODO ESTO COMENZÓ CON UN ÚNICO PARCHE DE TIERRA HACE ' + year + ' AÑOS. HONESTAMENTE, ES DIFÍCIL INCLUSO RECORDAR CÓMO ERA LA VIDA EN ESE ENTONCES';
        displayStoryFarm17 = 'EL ANTERIOR DUEÑO GARANTIZA SU RENTABILIDAD. ME DICEN QUE LAS DÁTILES ESTARÁN LISTAS AL FINAL DE CADA VERANO Y LOS HIGOS A FINALES DE LA PRIMAVERA. LAS GRANADAS ESTARÁN LISTAS A PRINCIPIOS DEL INVIERNO, LUEGO LAS UVAS DEBERÍAN LLEGAR UNAS SEMANAS MÁS TARDE, PERO SON INCONSTANTE';
        displayStoryOlives = 'HAN PASADO OCHO LARGOS AÑOS DESDE QUE TÚ HUBIERAS PLANTADO TU OLIVAR. FINALMENTE LOS ÁRBOLES SON MADUROS, CADA RAMA CARGADA DE FRUTOS MADUROS. Y DEBERÍAN LLEGAR A LA MISMA ÉPOCA CADA AÑO A PARTIR DE AHORA';

        displayStoryWarehouse0 = 'ESTE LUGAR ES ALTAMENTE RECOMENDABLE';
        displayStoryWarehouse1 = '«LO QUE ES COMÚN PARA LA MAYORÍA RECIBE LA MENOR CANTIDAD DE ATENCIÓN»<br>—ARISTÓTELES';
        displayStoryWarehouse2 = '«EN LA MAYORÍA DE LOS HOMBRES HAY TAL AMOR POR LOS MÉTODOS PROBADOS Y TAL TEMOR A LOS EXPERIMENTOS, QUE PROBABLEMENTE NO ACTUARÁN EN CONSECUENCIA HASTA MUCHO DESPUÉS DE QUE SEA SEGURO HACERLO»<br>—HERBERT SPENCER';

        displayStoryHands0 = 'HAS EMPLEADO A TU PRIMER HOMBRE. SU NOMBRE ES JUAN';
        displayStoryHands1 = 'JUAN TIENE UN HERMANO QUE BUSCA TRABAJO. PODRÍAS UTILIZAR OTRO BUEN HOMBRE';
        displayStoryHands2 = 'PODEMOS PERMITIRNOS UN HOMBRE NUEVO. LOS HERMANOS SUGEREN UN AMIGO CERCANO';
        displayStoryHands3 = 'USTED EMPLEA A OTRO HOMBRE SUGERIDO POR LOS HERMANOS';
        displayStoryHands4 = 'ES HORA DE CONTRATAR DE NUEVO. CORRES LA PALABRA Y CONTRATAS A OTRO HOMBRE';
        displayStoryHands5 = 'MUCHAS MANOS HACEN EL TRABAJO LIGERO, COMO DICEN';
        displayStoryHands6 = 'AHORA QUE USTED ES DUEÑO DE SU PROPIEDAD, TU VECINO PREGUNTA SI PUEDE QUEDARSE Y TRABAJAR PARA USTED';
        displayStoryHands7 = 'LOS HIJOS DE TU VECINO TIENEN ESPALDA FUERTE Y ESTÁN LISTOS PARA TRABAJAR. CONTRATAS AL HIJO MAYOR';
        displayStoryHands8 = 'USTED EMPLEA AL NIÑO MEDIO DE SU VECINO';
        displayStoryHands9 = 'EL CHICO PEQUEÑO DEL VECINO ESTÁ LISTO PARA UNIRSE';
        displayStoryHands10 = 'JUAN CONOCE ALGUNOS HOMBRES BUENOS. TRAE OTRO';
        displayStoryHands11 = 'TU VECINO TIENE UN CUÑADO QUE BUSCA TRABAJO. ÉL TE LO TRAE';
        displayStoryHands12 = 'TODO EL MUNDO SABE QUE ERES A QUIÉN DEBES VER PARA TRABAJAR. SE FORMA UN GRUPO EN TU PUERTA. ELIGES AL HOMBRE MÁS ALTO DE LA MULTITUD';
        displayStoryHands13 = 'VES A OTRO HOMBRE QUE PARECE FUERTE Y DICES QUE ENTRE';
        displayStoryHands14 = 'UN HOMBRE PEQUEÑO SE ACERCA A TI. DICE QUE QUIZÁS NO PARECE MUCHO PERO ES TENAZ. LO AGREGAS A LA LISTA';
        displayStoryHands15 = 'TANTOS MUNDOS Y TIERRAS PARA ELABORAR KARMA. ¡TANTAS MUCHAS LECCIONES QUE APRENDER!<br><br>GURÚ GRANTH SAHIB, ANG 7';
        displayStoryHands16 = 'AUN HAY MUCHO PARA ELEGIR. DEJASTE A OTRO TIPO DE APARIENCIA FUERTE ATRAVESAR LA PUERTA';
        displayStoryHands17 = 'MIENTRAS SELECCIONAS EL PRÓXIMO CONTRATADO ENTRE LA MULTITUD QUE ESPERA, UNO DE TUS HOMBRES TE TRAE LA NOTICIA: JUAN SE ENFERMO CON FIEBRE ANOCHE NOCHE Y NO SE DESPERTÓ ESTA MAÑANA. ES UNA PENA. PARA REEMPLAZARLO DEJAS ENTRAR UNO MÁS';
        displayStoryHands18 = 'EL HERMANO DE JUAN ESTÁ ENFERMO DE DUELO Y NO PUEDE TRABAJAR. DESAFORTUNADAMENTE TAMBIÉN NECESITARÁ SER REEMPLAZO. ELEGES DOS MÁS DE LA MULTITUD';
        displayStoryHands19 = 'HAY MÁS PERSONAS AQUÍ DE LAS QUE TENEMOS OPORTUNIDADES, PERO NECESITAMOS UNO MÁS';
        displayStoryHands20 = 'ESCLAVOS, OBEDECED SIEMPRE EN TODO SENTIDO A VUESTROS AMOS TERRENALES, NO SÓLO CUANDO OS ESTÁN OBSERVANDO, SINO TODO EL TIEMPO, POR TEMOR A DIOS<br><br>COLOSENSES 3:22';
        displayStoryHands21 = 'TODOS LOS DÍAS ALGUIEN PREGUNTA: ¿ESTÁS CONTRATANDO? BUENO, HOY SOMOS. USTED EMPLEA A UN HOMBRE NUEVO QUE LE FUE PRESENTADO POR UNO DE SUS GRANJEROS';
        displayStoryHands22 = 'A VECES NO PUEDES EVITAR ODIO A TODAS ESTAS MALDITAS GENTE';
        displayStoryHands23 = 'BIEN, SIEMPRE HAY MÁS TRABAJO POR HACER, Y NO SE HARÁ SOLO';
        displayStoryHands24 = 'NUEVO MUCHACHO EMPIEZA HOY. PARECE BASTANTE JOVEN, PERO PARECE ENTUSIASMADO';
        displayStoryHands25 = 'EL NIÑO NUEVO PERDIÓ UNA MANO EN UN ACCIDENTE POCAS HORAS DESPUÉS DE COMENZAR SU PRIMER DÍA. UNA TRAGEDIA PARA SU FAMILIA, SEGURO. BIEN, EL SEÑOR DA Y EL SEÑOR QUITA, COMO NOS DICE JOB. CONTRATAS A DOS MÁS EN LUGAR DE SOLO UNO';
        displayStoryHands26 = 'DIOS MÍO, ESE POBRE NIÑO. DIFÍCIL SACAR TODA ESA SANGRE DE TU MENTE';
        displayStoryHands27 = 'INCÓMODA SE ENCUENTRA LA CABEZA QUE LLEVA UNA CORONA<br><br>LA SEGUNDA PARTE DE ENRIQUE EL CUARTO 3.1.1735';
        displayStoryHands28 = 'LOS HOMBRES QUE HAN ESTADO CUIDANDO LO QUE AHORA ES TU CAMPO DE CEBADA SE PRESENTAN A TRABAJAR A LA MAÑANA SIGUIENTE, CON LA ESPERANZA DE UNIRSE A TU PERSONAL Y MANTENER SUS EMPLEOS. SU LÍDER DA UN PASO ADELANTE Y TÚ LE DA LA BIENVENIDA EL HOMBRE A LA NUEVA VIDA DE ÉL, MUY SIMILAR A LA ÚLTIMA DE ÉL';
        displayStoryHands29 = 'EL SIGUIENTE HOMBRE ENTRA EN SILENCIO POR LA PUERTA Y COMIENZA A TRABAJAR COMO SI NADA HABIERA CAMBIADO. BUENO... SUPONES, A ÉL, NADA MUCHO HA';
        displayStoryHands30 = 'ESTE SIGUIENTE COMPAÑERO PARECE UN CLIENTE DIFÍCIL, PERO TAMBIÉN PARECE QUE HA ESTADO TRABAJANDO GRANOS TODA SU VIDA. PROBABLEMENTE UN BUEN HOMBRE PARA TENER EN EL EQUIPO';
        displayStoryHands31 = 'BUENO SANTO, ESTO ESTÁ TOMANDO TODO EL DÍA. SI, SI, ENTREN, ENTREN SEÑORES';
        displayStoryHands32 = 'ALGUNOS DE ESTOS NIÑOS PARECE QUE SEGURAMENTE SE BENEFICIARÍAN DE UNA BUENA COMIDA';
        displayStoryHands33 = 'MUCHOS HOMBRES DE ESTA REGIÓN CONFIAN EN USTED AHORA PARA SU MEDIO DE VIDA; LOS HOMBRES *Y* SUS FAMILIAS';
        displayStoryHands34 = 'TOLERARÉ TODA ESTA BEBIDA<br>SI ME AYUDA A PASAR LOS DÍAS<br>—INTERPOL';
        displayStoryHands35 = 'FELICIDADES. USTED EMPLEA A TODOS LOS QUE CONOCE';

        displayStoryFound = '«TENGO HIJOS, TENGO RIQUEZA,» CON TALES PENSAMIENTOS EL TONTO SE TORMENTA. PERO SI NO ERES EL DUEÑO DE TU PROPIO SER, ¿CÓMO PUEDES DECIR QUE LOS HIJOS TE PERTENECEN? ¿O RIQUEZA?<br><br>DHAMMAPADA 5.62';
        displayStoryFoundCopper = '¡UNA PAREJA DE SENDERISTAS EN TU MONTAÑAS HAN DESCUBIERTO PEPITAS DE LO QUE PARECE SER ORICALCO!';
        displayStoryMineScout = 'TUS EXPLORADORES ENCONTRARON UN VETA RICO EN TUS COLINAS ORIENTAL';
        displayStoryMineDig = 'LOS MINERALES TIENEN VIDA PROPIA AL IGUAL QUE LOS VEGETALES, Y LOS ANIMALES Y LOS PÁJAROS, Y LOS SERES HUMANOS<br><br>PHÁP CHÁNH TRUYỀN, PARTE 5';
        displayStoryFoundry = '«EL ‘HOLOCENO’ HA TERMINADO. EL JARDÍN DEL EDÉN YA NO EXISTE. HEMOS CAMBIADO TANTO EL MUNDO QUE LOS CIENTÍFICOS DICEN QUE ESTAMOS EN UNA NUEVA ERA GEOLÓGICA: EL ‘ANTROPOCENO’. LA ERA DE LA HUMANIDAD. DEBEMOS IR MÁS ALLÁ DE LA CULPA Y PONERNOS A LA OBRA PRÁCTICA»<br>—SIR DAVID FREDERICK ATTENBOROUGH';
        displayStoryTribute = 'EL JEFE MILITAR REY LOCAL FINALMENTE HA OÍDO HABLAR DE TI. SU EMISARIO TE DICE: «POR SUPUESTO, SE DEBEN IMPONER ARANCELES»';

        displayStoryResidenceFirstVisit = 'NO HAY LUGAR COMO EL HOGAR: TU CAMPAMENTO, ANÓNIMO ENTRE LOS CIENTOS DE OTROS EXACTAMENTE COMO ÉL QUE SE ENCUENTRAN AQUÍ, EN ESTE VALLE ANGOSTO Y ÁRIDO, DONDE ALQUILAS ESTE TROZO DE TIERRA POR UN PRECIO EXORBITANTE';
        displayStoryResidence00 = 'VIVIR EN MI PROPIA TIERRA SEGURO ME HARÁ MÁS FÁCIL LLEGAR AL TRABAJO POR LA MAÑANA';
        displayStoryResidence01 = 'POR FIN UN POCO DE ESPACIO PARA ESTIRAR MIS PIERNAS';
        displayStoryResidence02 = 'SUPERFICIE MÁS QUE SUFICIENTE EN ESTE PRADERA PARA UNA FINCA MODESTA, CREO QUE';
        displayStoryResidence03 = '';
        displayStoryResidence04 = '';
        displayStoryResidence05 = '';
        displayStoryResidence06 = '';
        displayStoryResidence07 = '';
        displayStoryResidence08 = '';
        displayStoryResidence09 = '';
        displayStoryResidence10 = '';
        displayStoryResidence11 = '';
        displayStoryResidence12 = '';
        displayStoryResidence13 = '';

        displayStoryVillage0 = 'NECESITARÁ MADERA PARA LA FRAGUA';
        displayStoryVillage1 = 'AHORA PODEMOS CONSTRUIR';
        displayStoryVillage2 = 'DEBEMOS TENER ALGO DE LEY Y ORDEN';
        displayStoryVillage3 = 'LA GENTE NECESITA HOGARES';
        displayStoryVillage4 = 'MÁS APARTAMENTOS SIGNIFICA MÁS INQUILINOS, MÁS INQUILINOS SIGNIFICA MÁS RENTA';
        displayStoryVillage5 = 'LAS ESPECIAS DEL MERCADO SON VERDADERAMENTE FRAGANTES';
        displayStoryVillage6 = 'LOS CONSTRUCTORES ASEGURAN QUE NO HAY PELIGRO';
        displayStoryVillage7 = 'LOS CIUDADANOS LLEGAN DEL CAMPO AHORA EN BUSCA DE OPORTUNIDADES';
        displayStoryVillage8 = '«ENSEÑA A UN HOMBRE A PESCAR Y LO ALIMENTARÁS TODA LA VIDA»<br>—MAIMÓNIDES<br><br>(Rendimiento Máximo Por Cosecha +33%)';
        displayStoryVillage9 = 'VIVIR EN UN BUEN LUGAR<br><br>DÀO DÉ JĪNG 8:5';
        displayStoryVillage10 = 'LOS CABALLOS IMPULSAN EL PROGRESO';
        displayStoryVillage11 = 'LOS VERDADEROS SIERVOS DE DIOS SON LOS QUE VIAJAN POR LA TIERRA CON GRACIA, Y CUANDO LOS IGNORANTES SE DIRIGEN A LES GROSERAMENTE, RESPONDEN CON PALABRAS DE PAZ<br><br>’AL-FURQĀN 63';
        displayStoryVillage12 = '«SÓLO DESEAN DOS COSAS, PAN Y CIRCOS»<br>—JUVENAL';
        displayStoryVillage13 = '«CONTRAER NUEVAS DEUDAS NO ES LA MANERA DE PAGAR LAS VIEJAS»<br>—GEORGE WASHINGTON';
        displayStoryVillage14 = 'TIENES DERECHO A TRABAJAR, PERO NO TIENES DERECHO A LOS FRUTOS DE TU TRABAJO. NUNCA CREAS QUE ERES LA CAUSA DE LOS RESULTADOS DE TUS ELECCIONES. TRABAJAR DURO Y SER EQUILIBRIO EN EL ÉXITO Y EL FRACASO. ... LOS QUE BUSCAN DISFRUTAR LOS FRUTOS DE SUS OBRAS SON MISERABLES.<br><br>BHAGAVAD-GĪTĀ 2.47-49';
        displayStoryVillage15 = 'LA LIMPIEZA ES DIVINO';
        displayStoryVillage16 = 'ODIAN AL QUE SERMONA EN LA PUERTA, Y ABORRECEN AL QUE HABLA LA VERDAD<br><br>AMÓS 5:10';
        displayStoryVillage17 = 'LA PLACA DE BRONCE SOBRE LA BASE DE MÁRMOL ROSA DICE:<br><br>≈ LAS 8 VIRTUDES ≈<br><br>♠<br>• HONESTIDAD •<br>DECIR LA VERDAD<br>♠<br>• HONOR •<br>HACER LO CORRECTO<br>♠<br>• VALOR •<br>MANTENERSE CONTRA LA INJUSTICIA<br>♠<br>• SACRIFICIO •<br>COMPARTE TUS BENDICIONES<br>♠<br>• COMPASIÓN •<br>SER AMABLE CON LOS DÉBILES<br>♠<br>• JUSTICIA •<br>SER JUSTO CON TODOS<br>♠<br>• ESPIRITUALIDAD •<br>ESCUCHA LA LUZ<br>♠<br>• HUMILDAD •<br>RESISTIR ORGULLO<br>♣';

        displayNamePlayer = '«¿Cómo te llamas, ciudadano?»';

        displayGoToPraediumFromRes = 'VOLVER A TUS TIERRAS →';
        displayGoToResidence = '← IR A TU RESIDENCIA';
        displayGoToTownship = 'IR AL MUNICIPIO →';
        displayGoToPraedium = '← REGRESAR A TU PRAEDIUM';
        displayGoToPort = 'VIAJAR AL PUERTO →';
        displayGoToTownshipFromPort = '← REGRESAR A TU PROVINCIA';

        displayVillageTitle0 = 'El Asentamiento de';
        displayVillageTitle1 = 'El Puesto Avanzado de';
        displayVillageTitle2 = 'El Caserío de';
        displayVillageTitle3 = 'La Aldea de';
        displayVillageTitle4 = 'El Pueblo de';
        displayVillageTitle5 = 'La Ciudad de';
        displayVillageTitle6 = 'La Capital de';

        displayCitizens = 'Ciudadanos';
        displayPilgrims = 'Peregrinos';
        displayDemographics = 'Demografía';
        displayFiat = 'Fiduciario';
        displayTreasury = 'Tesorería';
        displayAsSpent = 'Gastado';
        displayLifetimeRevenues = 'Ingresos de Por Vida';
        displayLifetimeCosts = 'Costos de Por Vida';
        displayIncome = 'Ingresos';
        displayPnL = 'Pérdidas y Ganancias';
        displayRent = 'Alquiler';
        displayRealEstate = 'Inmueble';
        displayMarket = 'Minorista';
        displayHusbandry = 'Ganadería';
        displayConjunction = 'Conjunción';
        displayTourism = 'Turismo';
        displayWorship = 'Adoración';
        displayTribute = 'Homenaje';
        displayMilitary = 'Militar';
        displayStudy = 'Estudio';
        displayTaxes = 'Impuestos';
        displayMateriel = 'Material';
        displayPonies = 'Ponis';
        displayCavalry = 'Caballería';
        displayPrayers = 'Oraciones';
        displayChampionships = 'Campeonatos';
        displayChance = 'oportunidad';
        displayScripture = 'Escritura';
        displayRelic = 'Artefactos';
        displayMessiahs = 'Mesías';
        displayRats = 'Ratas';
        displayStatistics = 'Estadísticas';
        displayOffense = 'OFE';
        displayDefense = 'DEF';

        displayLoaves = 'Hogazas';
        displayOil = 'Aceite';
        displayBeer = 'Cerveza';
        displayWine = 'Vino';
        displaySyrup = 'Jarabe';
        displayJuice = 'Jugo';
        displayDriedFigs = 'Higos Secos al Sol';
        displayTrinkets = 'Baratijas';
        displayAmountProduced = 'Unidades<br>Producidas';
        displayAmountSpent = 'Unidades<br>Gastadas';

        displayConsumes = 'Consume';
        displayUsed = 'Utilizado';
        displayBakery = 'Panadería';
        displayOliveMill = 'Almazara';
        displayBrewery = 'Cervecería';
        displayWinery = 'Lagar';
        displayKitchen = 'Cocina';
        displayPress = 'Exprimidor';
        displayGreenhouse = 'Invernadero';
        displayAtelier = 'Atelier';

        displayForewordA = 'Es el año 200 a.C. y eres un humilde aparcero tartésico que se gana la vida modestamente bajo el brutal sol del Mediterráneo en la Galilea palestina. Desde el amanecer hasta el anochecer trabajas la implacable tierra calcárea sin nada más que tus propias manos y un palo afilado.';
        displayForewordScripture = '«¡O Creador del mundo material, O Santo! ¿A qué distancia del fuego? ¿A qué distancia del agua? ¿A qué distancia de los manojos consagrados de baresma? ¿A qué distancia de los fieles?»';
        displayForewordSource = 'Vendidad 8:6';
        displayForewordB = '¿Tiene lo necesario para redactar la constitución de una ciudad-Estado que iluminará el camino durante siglos y al mismo tiempo logrará personalmente una iluminación trascendental y la absolución de toda una vida de pecados? ¡Ahora es tu oportunidad!';
        displayForewordLabel = 'ESTOY LISTO PARA COMENZAR';

        displayNewLanguage = 'El idioma actual ahora está configurado en español.';
        displayLanguageQuote = '<div id="divSystemMessageScripture">«No hay conocimiento verdadero sin fe recta, ninguna conducta virtuosa es posible sin conocimiento, sin virtud no hay liberación, y sin liberación, no nirvana.»</div><div id="divSystemMessageSource">Uttaradhyayana 28:30</div>';

        displayInfoMadeWith = 'Para Dylan, DJ, Simone, Carlos, y Gustavo. Los amo a todos mucho.<br><br>Hecho con CodePen, el GNU Image Manipulation Program, GitHub, Inkscape y Visual Studio Code.';
        displayInfoDedication = 'Dedicado a Lori y Corey Cole, Jeff y ’Manda Dee, Richard Garriott, ALexis JAnson, Chris “Pumaman” Jones, Denis Loubet, David “aniwey” L., Tom Rothamel, Tim Sweeney y Michael Townsend, y en memoria amorosa de Travontee’ Flemming, Francisco Furlan, La’Voris McKeever y Philip J Reed, VSc. Realmente, realmente desearía que estuvieran aquí.';
        displayInfoThanks = 'Agradecimientos especiales a Mohammad Alavi, Sheila Bailey, Todd T. Brannon, Dave y Anna Davis, Miguel Angel Droz III, Derek Evans, Kenneth Garagnon, Sean Glavin, Hayley Hackett, Marty Hirsch, Leif y Marisol Johansen, David Macaulay, la familia Méndez, Brian Moran, Flathead Mike Niles, Jim Shepperd, Grant Sutherland, Benjamin A. Taylor y W3Schools.';
        displayInfoScripture = '<div id="divSystemMessageScripture">«Si escuchas el Camino una mañana y mueres esa noche, mueres contento.»</div><div id="divSystemMessageSource">Analectas 4:8</div>';

        displayBoilerplate = 'ESTE SOFTWARE SE PROPORCIONA *TAL CUAL*, SIN GARANTÍA DE NINGÚN TIPO.';
        displayLegalQuote = '<div id="divSystemMessageScripture">«Os ordeno que protejáis a vuestros semejantes.»</div><div id="divSystemMessageSource">—Ḥamza ibn ‘Alī ibn ʾAḥmad</div>';

        displayOptionsFlavour = '«Ansiedad es el vértigo de la libertad.»<div id="divOptionsSource">—Søren Kierkegaard</div>';

        displayBoxCopy = 'Ponte las sandalias de un sencillo agricultor de cereales tartésico en el año 200 a.C. ¿¿Tiene lo necesario para redactar la constitución de una ciudad-Estado que iluminará el camino durante siglos y logrará personalmente una iluminación trascendental, señor??<br><br>Déjese transportar literalmente a la antigua época romana mediante esta simulación por computadora de vanguardia que lo coloca a USTED en el corazón de la trepidante ACCIÓN AGRÍCOLA REAL!';

        displayHeir = 'ELEGIR UN HEREDERO';
        displayEndButton = 'CONCLUIR';

        displayModCodeLabel = '<i>¡LA DISCRECIÓN DEL USUARIO ES FUERTEMENTE ACONSEJADO!</i><br>¡No copie en esta ventana ningún código que no comprenda completamente y/o en el que no confíe!';
        displayModCodeTextArea = 'Pegue su modCode aquí';
        displaySubmitModCode = 'ENTREGAR MODCODE';
        displayDismissMods = 'HE TERMINADO';
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////

    const divider = '<div class="divider">♦♦♦ ♦ ♦♦♦</div>';
    displayInfoFinal = '<div id="divInfoTitle">' + displayGameTitle + '<br><span id="spanInfoVersion">v' + version + ' (<span id="spanInfoCC0">CCØ</span>) MMXXIV</span></div>';
    displayInfoFinal += displayInfoMadeWith + '<br><br>' + displayInfoDedication + '<br><br>' + displayInfoThanks;
    displayInfoFinal += divider + displayInfoScripture;
    displayLegalFinal = displayBoilerplate + divider + displayLegalQuote;
    displayOptionsFlavourFinal = divider + displayOptionsFlavour;
    document.title = displayGameTitle + ' - ' + displayGameEdition;
    UpdateDisplay();
    if (bark) { SystemMessage(displayNewLanguage + divider + displayLanguageQuote); }
}



// End of Document